apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: prometheus-server
  namespace: monitor
  labels:
    app: prometheus-server
spec:
  serviceName: prometheus-service
  replicas: 1
  selector:
    matchLabels:
      app: prometheus-server
  template:
    metadata:
      labels:
        app: prometheus-server
    spec:
      initContainers:
        - name: fix-permissions
          image: docker.m.daocloud.io/busybox
          command: [chown, -R, "nobody:nobody", /prometheus/]
          volumeMounts:
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      containers:
        - name: prometheus
          image: prom/prometheus:v2.26.0
          args:
            - "--config.file=/etc/prometheus/prometheus.yml"
            - "--storage.tsdb.path=/prometheus/"
          ports:
            - containerPort: 9090
          volumeMounts:
            - name: prometheus-config-volume
              mountPath: /etc/prometheus/
            - name: prometheus-storage-volume
              mountPath: /prometheus/
      volumes:
        - name: prometheus-config-volume
          configMap:
            defaultMode: 420
            name: prometheus-server-conf
  volumeClaimTemplates:
    - metadata:
        name: prometheus-storage-volume
        labels:
          app: prometheus-server
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 20Gi
