apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: grafana
  namespace: monitor
spec:
  serviceName: grafana
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      name: grafana
      labels:
        app: grafana
    spec:
      securityContext:
        runAsUser: 472
        fsGroup: 472
      containers:
        - name: grafana
          image: grafana/grafana:7.5.5
          ports:
            - name: grafana
              containerPort: 3000
          env:    
            - name: GF_INSTALL_PLUGINS
              value: "grafana-clock-panel 1.0.1,grafana-simple-json-datasource 1.3.5,grafana-kubernetes-app 1.0.1"
          resources:
            limits:
              memory: "1Gi"
              cpu: "1000m"
            requests:
              memory: 500M
              cpu: "500m"
          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana
            - name: grafana-datasources
              mountPath: /etc/grafana/provisioning/datasources
              readOnly: false
      volumes:
        - name: grafana-datasources
          configMap:
            defaultMode: 420
            name: grafana-datasources
  volumeClaimTemplates:
    - metadata:
        name: grafana-storage
        labels:
          app: grafana
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 10Gi
