#!/bin/bash -e

cd $(dirname $0)/..

ENV=${1:-test}
echo "Deploying grafana with config for environment: ${ENV}..."

kubectl apply -f grafana/grafana-datasource.yaml
kubectl apply -f grafana/statefulset.yaml
kubectl apply -f grafana/service.yaml
kubectl patch statefulset grafana -n monitor -p '{"spec":{"template":{"metadata":{"annotations":{"timestamp": '\"$(date +'%s')\"' }}}}}'
kubectl rollout status statefulset/grafana -n monitor
