#!/bin/bash -e

cd $(dirname $0)/..

ENV=${1:-test}
echo "Destroying node-exporter with config for environment: ${ENV}..."

kubectl delete -f node-exporter/daemonset.yaml
kubectl delete -f node-exporter/service.yaml
